# Generated by Django 2.2.5 on 2019-09-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
    ]
